plugins {
    id 'java'
    id 'application'
    //JavaFX 플러그인
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

group = 'com'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    //이미지
    implementation("net.coobird:thumbnailator:0.4.21")
    //영상
    implementation("org.bytedeco:ffmpeg:8.1.2-1.5.14")
}

javafx {
    version = "21"
    modules = [ 'javafx.controls', 'javafx.fxml' ]
}

application {
    mainClass = 'com.pixelflux.main'
}

test {
    useJUnitPlatform()
}